//*
// Groups V2 protobuf definitions for Signal.
// Subset needed for fetching group details.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: Groups.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Member_Role int32

const (
	Member_UNKNOWN       Member_Role = 0
	Member_DEFAULT       Member_Role = 1
	Member_ADMINISTRATOR Member_Role = 2
)

// Enum value maps for Member_Role.
var (
	Member_Role_name = map[int32]string{
		0: "UNKNOWN",
		1: "DEFAULT",
		2: "ADMINISTRATOR",
	}
	Member_Role_value = map[string]int32{
		"UNKNOWN":       0,
		"DEFAULT":       1,
		"ADMINISTRATOR": 2,
	}
)

func (x Member_Role) Enum() *Member_Role {
	p := new(Member_Role)
	*p = x
	return p
}

func (x Member_Role) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Member_Role) Descriptor() protoreflect.EnumDescriptor {
	return file_Groups_proto_enumTypes[0].Descriptor()
}

func (Member_Role) Type() protoreflect.EnumType {
	return &file_Groups_proto_enumTypes[0]
}

func (x Member_Role) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Member_Role.Descriptor instead.
func (Member_Role) EnumDescriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{0, 0}
}

type AccessControl_AccessRequired int32

const (
	AccessControl_UNKNOWN       AccessControl_AccessRequired = 0
	AccessControl_ANY           AccessControl_AccessRequired = 1
	AccessControl_MEMBER        AccessControl_AccessRequired = 2
	AccessControl_ADMINISTRATOR AccessControl_AccessRequired = 3
	AccessControl_UNSATISFIABLE AccessControl_AccessRequired = 4
)

// Enum value maps for AccessControl_AccessRequired.
var (
	AccessControl_AccessRequired_name = map[int32]string{
		0: "UNKNOWN",
		1: "ANY",
		2: "MEMBER",
		3: "ADMINISTRATOR",
		4: "UNSATISFIABLE",
	}
	AccessControl_AccessRequired_value = map[string]int32{
		"UNKNOWN":       0,
		"ANY":           1,
		"MEMBER":        2,
		"ADMINISTRATOR": 3,
		"UNSATISFIABLE": 4,
	}
)

func (x AccessControl_AccessRequired) Enum() *AccessControl_AccessRequired {
	p := new(AccessControl_AccessRequired)
	*p = x
	return p
}

func (x AccessControl_AccessRequired) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AccessControl_AccessRequired) Descriptor() protoreflect.EnumDescriptor {
	return file_Groups_proto_enumTypes[1].Descriptor()
}

func (AccessControl_AccessRequired) Type() protoreflect.EnumType {
	return &file_Groups_proto_enumTypes[1]
}

func (x AccessControl_AccessRequired) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AccessControl_AccessRequired.Descriptor instead.
func (AccessControl_AccessRequired) EnumDescriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{1, 0}
}

type Member struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          []byte                 `protobuf:"bytes,1,opt,name=userId,proto3" json:"userId,omitempty"`
	Role            Member_Role            `protobuf:"varint,2,opt,name=role,proto3,enum=signalservice.Member_Role" json:"role,omitempty"`
	ProfileKey      []byte                 `protobuf:"bytes,3,opt,name=profileKey,proto3" json:"profileKey,omitempty"`
	Presentation    []byte                 `protobuf:"bytes,4,opt,name=presentation,proto3" json:"presentation,omitempty"`
	JoinedAtVersion uint32                 `protobuf:"varint,5,opt,name=joinedAtVersion,proto3" json:"joinedAtVersion,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Member) Reset() {
	*x = Member{}
	mi := &file_Groups_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Member) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Member) ProtoMessage() {}

func (x *Member) ProtoReflect() protoreflect.Message {
	mi := &file_Groups_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Member.ProtoReflect.Descriptor instead.
func (*Member) Descriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{0}
}

func (x *Member) GetUserId() []byte {
	if x != nil {
		return x.UserId
	}
	return nil
}

func (x *Member) GetRole() Member_Role {
	if x != nil {
		return x.Role
	}
	return Member_UNKNOWN
}

func (x *Member) GetProfileKey() []byte {
	if x != nil {
		return x.ProfileKey
	}
	return nil
}

func (x *Member) GetPresentation() []byte {
	if x != nil {
		return x.Presentation
	}
	return nil
}

func (x *Member) GetJoinedAtVersion() uint32 {
	if x != nil {
		return x.JoinedAtVersion
	}
	return 0
}

type AccessControl struct {
	state             protoimpl.MessageState       `protogen:"open.v1"`
	Attributes        AccessControl_AccessRequired `protobuf:"varint,1,opt,name=attributes,proto3,enum=signalservice.AccessControl_AccessRequired" json:"attributes,omitempty"`
	Members           AccessControl_AccessRequired `protobuf:"varint,2,opt,name=members,proto3,enum=signalservice.AccessControl_AccessRequired" json:"members,omitempty"`
	AddFromInviteLink AccessControl_AccessRequired `protobuf:"varint,3,opt,name=addFromInviteLink,proto3,enum=signalservice.AccessControl_AccessRequired" json:"addFromInviteLink,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AccessControl) Reset() {
	*x = AccessControl{}
	mi := &file_Groups_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccessControl) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccessControl) ProtoMessage() {}

func (x *AccessControl) ProtoReflect() protoreflect.Message {
	mi := &file_Groups_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccessControl.ProtoReflect.Descriptor instead.
func (*AccessControl) Descriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{1}
}

func (x *AccessControl) GetAttributes() AccessControl_AccessRequired {
	if x != nil {
		return x.Attributes
	}
	return AccessControl_UNKNOWN
}

func (x *AccessControl) GetMembers() AccessControl_AccessRequired {
	if x != nil {
		return x.Members
	}
	return AccessControl_UNKNOWN
}

func (x *AccessControl) GetAddFromInviteLink() AccessControl_AccessRequired {
	if x != nil {
		return x.AddFromInviteLink
	}
	return AccessControl_UNKNOWN
}

// Group is the encrypted group state returned by the Groups V2 API.
type Group struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	PublicKey                 []byte                 `protobuf:"bytes,1,opt,name=publicKey,proto3" json:"publicKey,omitempty"`
	Title                     []byte                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`              // encrypted GroupAttributeBlob
	Description               []byte                 `protobuf:"bytes,11,opt,name=description,proto3" json:"description,omitempty"` // encrypted GroupAttributeBlob
	AvatarUrl                 string                 `protobuf:"bytes,3,opt,name=avatarUrl,proto3" json:"avatarUrl,omitempty"`
	DisappearingMessagesTimer []byte                 `protobuf:"bytes,4,opt,name=disappearingMessagesTimer,proto3" json:"disappearingMessagesTimer,omitempty"`
	AccessControl             *AccessControl         `protobuf:"bytes,5,opt,name=accessControl,proto3" json:"accessControl,omitempty"`
	Version                   uint32                 `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"` // group revision
	Members                   []*Member              `protobuf:"bytes,7,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *Group) Reset() {
	*x = Group{}
	mi := &file_Groups_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Group) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Group) ProtoMessage() {}

func (x *Group) ProtoReflect() protoreflect.Message {
	mi := &file_Groups_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Group.ProtoReflect.Descriptor instead.
func (*Group) Descriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{2}
}

func (x *Group) GetPublicKey() []byte {
	if x != nil {
		return x.PublicKey
	}
	return nil
}

func (x *Group) GetTitle() []byte {
	if x != nil {
		return x.Title
	}
	return nil
}

func (x *Group) GetDescription() []byte {
	if x != nil {
		return x.Description
	}
	return nil
}

func (x *Group) GetAvatarUrl() string {
	if x != nil {
		return x.AvatarUrl
	}
	return ""
}

func (x *Group) GetDisappearingMessagesTimer() []byte {
	if x != nil {
		return x.DisappearingMessagesTimer
	}
	return nil
}

func (x *Group) GetAccessControl() *AccessControl {
	if x != nil {
		return x.AccessControl
	}
	return nil
}

func (x *Group) GetVersion() uint32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *Group) GetMembers() []*Member {
	if x != nil {
		return x.Members
	}
	return nil
}

// GroupAttributeBlob is the decrypted format for title/description.
type GroupAttributeBlob struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Content:
	//
	//	*GroupAttributeBlob_Title
	//	*GroupAttributeBlob_Avatar
	//	*GroupAttributeBlob_DisappearingMessagesDuration
	//	*GroupAttributeBlob_DescriptionText
	Content       isGroupAttributeBlob_Content `protobuf_oneof:"content"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GroupAttributeBlob) Reset() {
	*x = GroupAttributeBlob{}
	mi := &file_Groups_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupAttributeBlob) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupAttributeBlob) ProtoMessage() {}

func (x *GroupAttributeBlob) ProtoReflect() protoreflect.Message {
	mi := &file_Groups_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupAttributeBlob.ProtoReflect.Descriptor instead.
func (*GroupAttributeBlob) Descriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{3}
}

func (x *GroupAttributeBlob) GetContent() isGroupAttributeBlob_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *GroupAttributeBlob) GetTitle() string {
	if x != nil {
		if x, ok := x.Content.(*GroupAttributeBlob_Title); ok {
			return x.Title
		}
	}
	return ""
}

func (x *GroupAttributeBlob) GetAvatar() []byte {
	if x != nil {
		if x, ok := x.Content.(*GroupAttributeBlob_Avatar); ok {
			return x.Avatar
		}
	}
	return nil
}

func (x *GroupAttributeBlob) GetDisappearingMessagesDuration() uint32 {
	if x != nil {
		if x, ok := x.Content.(*GroupAttributeBlob_DisappearingMessagesDuration); ok {
			return x.DisappearingMessagesDuration
		}
	}
	return 0
}

func (x *GroupAttributeBlob) GetDescriptionText() string {
	if x != nil {
		if x, ok := x.Content.(*GroupAttributeBlob_DescriptionText); ok {
			return x.DescriptionText
		}
	}
	return ""
}

type isGroupAttributeBlob_Content interface {
	isGroupAttributeBlob_Content()
}

type GroupAttributeBlob_Title struct {
	Title string `protobuf:"bytes,1,opt,name=title,proto3,oneof"`
}

type GroupAttributeBlob_Avatar struct {
	Avatar []byte `protobuf:"bytes,2,opt,name=avatar,proto3,oneof"`
}

type GroupAttributeBlob_DisappearingMessagesDuration struct {
	DisappearingMessagesDuration uint32 `protobuf:"varint,3,opt,name=disappearingMessagesDuration,proto3,oneof"`
}

type GroupAttributeBlob_DescriptionText struct {
	DescriptionText string `protobuf:"bytes,4,opt,name=descriptionText,proto3,oneof"`
}

func (*GroupAttributeBlob_Title) isGroupAttributeBlob_Content() {}

func (*GroupAttributeBlob_Avatar) isGroupAttributeBlob_Content() {}

func (*GroupAttributeBlob_DisappearingMessagesDuration) isGroupAttributeBlob_Content() {}

func (*GroupAttributeBlob_DescriptionText) isGroupAttributeBlob_Content() {}

// GroupResponse wraps Group with optional endorsements.
type GroupResponse struct {
	state                         protoimpl.MessageState `protogen:"open.v1"`
	Group                         *Group                 `protobuf:"bytes,1,opt,name=group,proto3" json:"group,omitempty"`
	GroupSendEndorsementsResponse []byte                 `protobuf:"bytes,2,opt,name=group_send_endorsements_response,json=groupSendEndorsementsResponse,proto3" json:"group_send_endorsements_response,omitempty"`
	unknownFields                 protoimpl.UnknownFields
	sizeCache                     protoimpl.SizeCache
}

func (x *GroupResponse) Reset() {
	*x = GroupResponse{}
	mi := &file_Groups_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GroupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GroupResponse) ProtoMessage() {}

func (x *GroupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_Groups_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GroupResponse.ProtoReflect.Descriptor instead.
func (*GroupResponse) Descriptor() ([]byte, []int) {
	return file_Groups_proto_rawDescGZIP(), []int{4}
}

func (x *GroupResponse) GetGroup() *Group {
	if x != nil {
		return x.Group
	}
	return nil
}

func (x *GroupResponse) GetGroupSendEndorsementsResponse() []byte {
	if x != nil {
		return x.GroupSendEndorsementsResponse
	}
	return nil
}

var File_Groups_proto protoreflect.FileDescriptor

const file_Groups_proto_rawDesc = "" +
	"\n" +
	"\fGroups.proto\x12\rsignalservice\"\xf3\x01\n" +
	"\x06Member\x12\x16\n" +
	"\x06userId\x18\x01 \x01(\fR\x06userId\x12.\n" +
	"\x04role\x18\x02 \x01(\x0e2\x1a.signalservice.Member.RoleR\x04role\x12\x1e\n" +
	"\n" +
	"profileKey\x18\x03 \x01(\fR\n" +
	"profileKey\x12\"\n" +
	"\fpresentation\x18\x04 \x01(\fR\fpresentation\x12(\n" +
	"\x0fjoinedAtVersion\x18\x05 \x01(\rR\x0fjoinedAtVersion\"3\n" +
	"\x04Role\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aDEFAULT\x10\x01\x12\x11\n" +
	"\rADMINISTRATOR\x10\x02\"\xd8\x02\n" +
	"\rAccessControl\x12K\n" +
	"\n" +
	"attributes\x18\x01 \x01(\x0e2+.signalservice.AccessControl.AccessRequiredR\n" +
	"attributes\x12E\n" +
	"\amembers\x18\x02 \x01(\x0e2+.signalservice.AccessControl.AccessRequiredR\amembers\x12Y\n" +
	"\x11addFromInviteLink\x18\x03 \x01(\x0e2+.signalservice.AccessControl.AccessRequiredR\x11addFromInviteLink\"X\n" +
	"\x0eAccessRequired\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\a\n" +
	"\x03ANY\x10\x01\x12\n" +
	"\n" +
	"\x06MEMBER\x10\x02\x12\x11\n" +
	"\rADMINISTRATOR\x10\x03\x12\x11\n" +
	"\rUNSATISFIABLE\x10\x04\"\xc8\x02\n" +
	"\x05Group\x12\x1c\n" +
	"\tpublicKey\x18\x01 \x01(\fR\tpublicKey\x12\x14\n" +
	"\x05title\x18\x02 \x01(\fR\x05title\x12 \n" +
	"\vdescription\x18\v \x01(\fR\vdescription\x12\x1c\n" +
	"\tavatarUrl\x18\x03 \x01(\tR\tavatarUrl\x12<\n" +
	"\x19disappearingMessagesTimer\x18\x04 \x01(\fR\x19disappearingMessagesTimer\x12B\n" +
	"\raccessControl\x18\x05 \x01(\v2\x1c.signalservice.AccessControlR\raccessControl\x12\x18\n" +
	"\aversion\x18\x06 \x01(\rR\aversion\x12/\n" +
	"\amembers\x18\a \x03(\v2\x15.signalservice.MemberR\amembers\"\xc3\x01\n" +
	"\x12GroupAttributeBlob\x12\x16\n" +
	"\x05title\x18\x01 \x01(\tH\x00R\x05title\x12\x18\n" +
	"\x06avatar\x18\x02 \x01(\fH\x00R\x06avatar\x12D\n" +
	"\x1cdisappearingMessagesDuration\x18\x03 \x01(\rH\x00R\x1cdisappearingMessagesDuration\x12*\n" +
	"\x0fdescriptionText\x18\x04 \x01(\tH\x00R\x0fdescriptionTextB\t\n" +
	"\acontent\"\x84\x01\n" +
	"\rGroupResponse\x12*\n" +
	"\x05group\x18\x01 \x01(\v2\x14.signalservice.GroupR\x05group\x12G\n" +
	" group_send_endorsements_response\x18\x02 \x01(\fR\x1dgroupSendEndorsementsResponseB-Z+github.com/gwillem/signal-go/internal/protob\x06proto3"

var (
	file_Groups_proto_rawDescOnce sync.Once
	file_Groups_proto_rawDescData []byte
)

func file_Groups_proto_rawDescGZIP() []byte {
	file_Groups_proto_rawDescOnce.Do(func() {
		file_Groups_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_Groups_proto_rawDesc), len(file_Groups_proto_rawDesc)))
	})
	return file_Groups_proto_rawDescData
}

var file_Groups_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_Groups_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_Groups_proto_goTypes = []any{
	(Member_Role)(0),                  // 0: signalservice.Member.Role
	(AccessControl_AccessRequired)(0), // 1: signalservice.AccessControl.AccessRequired
	(*Member)(nil),                    // 2: signalservice.Member
	(*AccessControl)(nil),             // 3: signalservice.AccessControl
	(*Group)(nil),                     // 4: signalservice.Group
	(*GroupAttributeBlob)(nil),        // 5: signalservice.GroupAttributeBlob
	(*GroupResponse)(nil),             // 6: signalservice.GroupResponse
}
var file_Groups_proto_depIdxs = []int32{
	0, // 0: signalservice.Member.role:type_name -> signalservice.Member.Role
	1, // 1: signalservice.AccessControl.attributes:type_name -> signalservice.AccessControl.AccessRequired
	1, // 2: signalservice.AccessControl.members:type_name -> signalservice.AccessControl.AccessRequired
	1, // 3: signalservice.AccessControl.addFromInviteLink:type_name -> signalservice.AccessControl.AccessRequired
	3, // 4: signalservice.Group.accessControl:type_name -> signalservice.AccessControl
	2, // 5: signalservice.Group.members:type_name -> signalservice.Member
	4, // 6: signalservice.GroupResponse.group:type_name -> signalservice.Group
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_Groups_proto_init() }
func file_Groups_proto_init() {
	if File_Groups_proto != nil {
		return
	}
	file_Groups_proto_msgTypes[3].OneofWrappers = []any{
		(*GroupAttributeBlob_Title)(nil),
		(*GroupAttributeBlob_Avatar)(nil),
		(*GroupAttributeBlob_DisappearingMessagesDuration)(nil),
		(*GroupAttributeBlob_DescriptionText)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_Groups_proto_rawDesc), len(file_Groups_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Groups_proto_goTypes,
		DependencyIndexes: file_Groups_proto_depIdxs,
		EnumInfos:         file_Groups_proto_enumTypes,
		MessageInfos:      file_Groups_proto_msgTypes,
	}.Build()
	File_Groups_proto = out.File
	file_Groups_proto_goTypes = nil
	file_Groups_proto_depIdxs = nil
}
