// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.29.3
// source: internal/proto/SealedSender.proto

//
// Copyright 2020 Signal Messenger, LLC.
// SPDX-License-Identifier: AGPL-3.0-only
//

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Outer structure of a Sealed Sender v1 message.
// This is parsed BEFORE decryption to extract the encrypted components.
type UnidentifiedSenderMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	EphemeralPublic  []byte                 `protobuf:"bytes,1,opt,name=ephemeral_public,json=ephemeralPublic" json:"ephemeral_public,omitempty"`    // 33-byte Curve25519 public key (0x05 prefix)
	EncryptedStatic  []byte                 `protobuf:"bytes,2,opt,name=encrypted_static,json=encryptedStatic" json:"encrypted_static,omitempty"`    // Encrypted static key (48 bytes: 32 key + 16 MAC)
	EncryptedMessage []byte                 `protobuf:"bytes,3,opt,name=encrypted_message,json=encryptedMessage" json:"encrypted_message,omitempty"` // Encrypted message content
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *UnidentifiedSenderMessage) Reset() {
	*x = UnidentifiedSenderMessage{}
	mi := &file_internal_proto_SealedSender_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnidentifiedSenderMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnidentifiedSenderMessage) ProtoMessage() {}

func (x *UnidentifiedSenderMessage) ProtoReflect() protoreflect.Message {
	mi := &file_internal_proto_SealedSender_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnidentifiedSenderMessage.ProtoReflect.Descriptor instead.
func (*UnidentifiedSenderMessage) Descriptor() ([]byte, []int) {
	return file_internal_proto_SealedSender_proto_rawDescGZIP(), []int{0}
}

func (x *UnidentifiedSenderMessage) GetEphemeralPublic() []byte {
	if x != nil {
		return x.EphemeralPublic
	}
	return nil
}

func (x *UnidentifiedSenderMessage) GetEncryptedStatic() []byte {
	if x != nil {
		return x.EncryptedStatic
	}
	return nil
}

func (x *UnidentifiedSenderMessage) GetEncryptedMessage() []byte {
	if x != nil {
		return x.EncryptedMessage
	}
	return nil
}

var File_internal_proto_SealedSender_proto protoreflect.FileDescriptor

const file_internal_proto_SealedSender_proto_rawDesc = "" +
	"\n" +
	"!internal/proto/SealedSender.proto\x12\fsignal.proto\"\x9e\x01\n" +
	"\x19UnidentifiedSenderMessage\x12)\n" +
	"\x10ephemeral_public\x18\x01 \x01(\fR\x0fephemeralPublic\x12)\n" +
	"\x10encrypted_static\x18\x02 \x01(\fR\x0fencryptedStatic\x12+\n" +
	"\x11encrypted_message\x18\x03 \x01(\fR\x10encryptedMessageB-Z+github.com/gwillem/signal-go/internal/proto"

var (
	file_internal_proto_SealedSender_proto_rawDescOnce sync.Once
	file_internal_proto_SealedSender_proto_rawDescData []byte
)

func file_internal_proto_SealedSender_proto_rawDescGZIP() []byte {
	file_internal_proto_SealedSender_proto_rawDescOnce.Do(func() {
		file_internal_proto_SealedSender_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_proto_SealedSender_proto_rawDesc), len(file_internal_proto_SealedSender_proto_rawDesc)))
	})
	return file_internal_proto_SealedSender_proto_rawDescData
}

var file_internal_proto_SealedSender_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_internal_proto_SealedSender_proto_goTypes = []any{
	(*UnidentifiedSenderMessage)(nil), // 0: signal.proto.UnidentifiedSenderMessage
}
var file_internal_proto_SealedSender_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_internal_proto_SealedSender_proto_init() }
func file_internal_proto_SealedSender_proto_init() {
	if File_internal_proto_SealedSender_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_proto_SealedSender_proto_rawDesc), len(file_internal_proto_SealedSender_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_proto_SealedSender_proto_goTypes,
		DependencyIndexes: file_internal_proto_SealedSender_proto_depIdxs,
		MessageInfos:      file_internal_proto_SealedSender_proto_msgTypes,
	}.Build()
	File_internal_proto_SealedSender_proto = out.File
	file_internal_proto_SealedSender_proto_goTypes = nil
	file_internal_proto_SealedSender_proto_depIdxs = nil
}
